<?php

namespace Database\Factories;

use App\Models\Jogador;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Time>
 */
class TimeFactory extends Factory
{
    protected static $nomesTimes = [
        "Flamengo",
        "Corinthians",
        "São Paulo",
        "Palmeiras",
        "Vasco da Gama",
        "Grêmio",
        "Internacional",
        "Atlético Mineiro",
        "Cruzeiro",
        "Botafogo",
        "Santos",
        "Bahia",
        "Sport Recife",
        "Fortaleza",
        "Athletico Paranaense",
        "Fluminense",
        "Goiás",
        "Coritiba",
        "Atlético Paranaense",
        "CSA",
        "Ceará",
        "Chapecoense",
        "América Mineiro",
        "Juventude",
        "Ponte Preta",
        "Náutico",
        "Santa Cruz",
        "Figueirense",
        "Vila Nova",
        "CRB",
        "Guarani",
        "Paysandu",
        "Remo",
        "Ituano",
        "Bragantino",
        "Botafogo-SP",
        "ABC",
        "Brasil de Pelotas",
        "Londrina",
        "Sampaio Corrêa",
        "Operário Ferroviário",
        "Tombense",
        "Água Santa",
        "Novorizontino",
        "Confiança",
        "Paraná Clube",
        "São Bento",
        "CSA",
        "Juazeirense",
        "Vitória",
        "Maringá",
        "Ferroviária",
        "Santa Cruz-RS",
        "Inter de Limeira",
        "Marcílio Dias",
        "XV de Piracicaba",
        "Criciúma",
        "Paysandu",
        "Remo",
        "Santos-AP",
        "Náutico-RR",
        "Atlético-GO",
        "Botafogo-PB",
        "Criciúma",
        "Joinville",
        "ASA",
        "Treze",
        "Madureira",
        "Volta Redonda",
        "Duque de Caxias",
        "Cabofriense",
        "Boavista",
        "Macará",
        "Universidad Católica",
        "Barcelona SC",
        "Emelec",
        "LDU Quito",
        "Independiente del Valle",
        "Aucas",
        "Deportivo Cuenca",
        "Talleres",
        "Boca Juniors",
        "River Plate",
        "Racing Club",
        "Independiente",
        "San Lorenzo",
        "Vélez Sarsfield",
        "Lanús",
        "Rosario Central",
        "Newell's Old Boys",
        "Huracán",
        "Estudiantes",
        "Colón",
        "Atlético Nacional",
        "Millonarios",
        "Santa Fe",
        "Deportivo Cali",
        "Junior Barranquilla",
        "América de Cali"
    ];

    public function definition(): array
    {
        return [
            'nome' => $this->faker->unique()->randomElement(self::$nomesTimes),       
            'cidade' => $this->faker->city,
            'estadio' => $this->faker->company . ' Stadium',   
        ];
    }

}
